// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  雛形確認用のサンプルコマンド（Phase 1 で削除する） */
	greet: (name: string) => __TAURI_INVOKE<string>("greet", { name }),
};

