// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  プロジェクト一覧を取得。 */
	listProjects: () => typedError<ProjectInfo[], AppError>(__TAURI_INVOKE("list_projects")),
	/**
	 *  プロジェクトを追加（既存フォルダ登録・新規作成）。GitHub から取得する場合は `clone_project`。
	 * 
	 *  `remote` を渡すと、ローカルの登録に続けて GitHub 上にリポジトリを作り、保存先として接続し、
	 *  初回の保存（変更があれば）と初回のアップロードまで行う（設計書 4.6）。途中で失敗しても
	 *  ローカルの登録は残る（保存先の無いプロジェクトとして使え、あとから `connect_remote` で接続できる）。
	 *  その場合は `AddProjectResult.remote.error` に 3 要素のエラーが入る。
	 */
	addProject: (id: string, displayName: string, path: string, owner: string, remoteUrl: string | null, remote: {
	/**  保存先（個人のログイン名、または Organization 名）。`list_owners` の `id` */
	owner: string,
	/**
	 *  リポジトリ名。省略時はプロジェクト名から作る（英数字・`-`・`_`・`.` のみ。日本語の名前などは
	 *  `hikae-<識別子>` にする）
	 */
	name: string | null,
	/**  非公開にする（既定の選択肢） */
	private: boolean,
	/**  公開にすることの警告を確認した。`private` が false のとき、これが true でなければ拒否する */
	public_confirmed: boolean,
	/**
	 *  同名の「空の」保存先がすでにあるとき、新しく作らずにそこへ接続する（利用者が確認したあとだけ true）。
	 *  空でない保存先、書き込めない保存先には接続しない（バックエンドが改めて確かめる）
	 */
	adopt_existing: boolean,
} | null) => typedError<AddProjectResult, AppError>(__TAURI_INVOKE("add_project", { id, displayName, path, owner, remoteUrl, remote })),
	/**
	 *  プロジェクトを一覧から外す（設計書 4.6、5章 E11）。
	 * 
	 *  外すのは、アプリの中の登録・プロジェクト別の設定・ファイル監視・取り込み／アップロード／自動保存の
	 *  実行計画だけ。フォルダの中身、`.git`、`refs/hikae/` の復元点、GitHub 上のリポジトリには触れない
	 *  （git も実行しない）。外した後に同じフォルダを登録し直せる（既存の `.git` と保存先を引き継ぐ）。
	 * 
	 *  実行中の操作（保存・取り込みなど）が終わるのを、直列キューで待ってから外す。外した直後に、
	 *  実行計画を捨てて監視の停止を促す（監視は、スケジューラの次の巡回で止まる）。
	 */
	removeProject: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("remove_project", { id })),
	/**  プロジェクトの状態を取得（未保存の変更、アップロード待ち、競合など）。 */
	projectStatus: (id: string) => typedError<SyncStatus, AppError>(__TAURI_INVOKE("project_status", { id })),
	/**  変更ファイル一覧を取得（読み取りのみ。解析は core-ops）。 */
	listChanges: (id: string) => typedError<ChangeFile[], AppError>(__TAURI_INVOKE("list_changes", { id })),
	/**
	 *  保存（commit）を実行。
	 * 
	 *  保存前に新規・変更ファイルのサイズを検査する（設計書 4.1 手順 1）。大きいファイルがあれば
	 *  何も保存せず、`size_check` に該当ファイルとサイズを入れて返す（エラーではない）。
	 *  画面は E07 / E08 の 2 択を出し、選択を `save_with_size_choice` で送って保存をやり直す。
	 */
	save: (id: string, message: string) => typedError<SaveResult, AppError>(__TAURI_INVOKE("save", { id, message })),
	/**  大きいファイルについての選択（E07 / E08）を添えて保存をやり直す。 */
	saveWithSizeChoice: (id: string, message: string, choice: SaveSizeChoice) => typedError<SaveResult, AppError>(__TAURI_INVOKE("save_with_size_choice", { id, message, choice })),
	/**
	 *  取り込む（fetch + merge）を実行。
	 * 
	 *  設定「取り込む前に未保存の変更を保存」が「確認する」で、未保存の変更があり取り込む内容もあるときは、
	 *  何も変更せず結果 `needs-save-confirmation` を返す（E06）。画面は確認の後、`save_confirmed` を
	 *  真にしてもう一度呼ぶ。このとき従来どおり、復元点 → 自動保存 → 取り込みの順で実行する。
	 */
	pull: (id: string, saveConfirmed: boolean) => typedError<PullResult, AppError>(__TAURI_INVOKE("pull", { id, saveConfirmed })),
	/**  アップロード（push）を実行。 */
	push: (id: string) => typedError<PushResult, AppError>(__TAURI_INVOKE("push", { id })),
	/**
	 *  履歴を取得。新しい順で `offset` 件目から最大 `limit` 件（ページ送り）。
	 *  重複の判定は全体で行うため、ページを跨いでも重複・欠落しない。
	 */
	listHistory: (id: string, offset: number, limit: number) => typedError<HistoryItem[], AppError>(__TAURI_INVOKE("list_history", { id, offset, limit })),
	/**  差分を取得（2つの時点の比較）。 */
	diff: (id: string, from: string, to: string, path: string | null) => typedError<DiffResult, AppError>(__TAURI_INVOKE("diff", { id, from, to, path })),
	/**  元に戻す操作のプレビュー（影響ファイル一覧）。 */
	restorePreview: (id: string, commit: string) => typedError<RestorePreviewData, AppError>(__TAURI_INVOKE("restore_preview", { id, commit })),
	/**
	 *  元に戻す実行。
	 * 
	 *  設定「元に戻した後に自動で保存」がオンで `save_memo`（画面が渡す文言。例:「10/4 18:02 の状態に
	 *  戻しました」）があれば、戻した内容を続けて保存する（既存の保存と同じ復元点・サイズ検査を通り、
	 *  戻す操作と同じ直列キューの 1 回の実行の中で行う）。保存で大きいファイルの確認が必要なときは、
	 *  戻す操作だけが成功し、保存はしない（画面の通常の保存の流れに任せる）。
	 */
	restore: (id: string, commit: string, saveMemo: string | null) => typedError<RestoreAllResult, AppError>(__TAURI_INVOKE("restore", { id, commit, saveMemo })),
	/**  現在の競合ファイルを取得。 */
	listConflicts: (id: string) => typedError<ConflictItem[], AppError>(__TAURI_INVOKE("list_conflicts", { id })),
	/**  競合を解消。 */
	resolveConflicts: (id: string, choices: ([string, ConflictChoice])[], keepOtherCopy: boolean) => typedError<null, AppError>(__TAURI_INVOKE("resolve_conflicts", { id, choices, keepOtherCopy })),
	/**
	 *  未保存の変更から保存メモの案を作る（ルールベース、設計書 10.3）。
	 *  読み取りのみのため直列キューは通さない。
	 */
	suggestMemo: (id: string) => typedError<string, AppError>(__TAURI_INVOKE("suggest_memo", { id })),
	/**  指定した保存時点の全ファイル一覧（読み取りのみ）。 */
	listFilesAt: (id: string, commit: string) => typedError<FileEntry[], AppError>(__TAURI_INVOKE("list_files_at", { id, commit })),
	/**
	 *  プロジェクト内のファイルを既定のアプリで開く。
	 *  相対パスはここで検証し、プロジェクト外（`..`・絶対パス・シンボリックリンク経由）は開かない。
	 *  読み取りのみのため直列キューは通さない。
	 */
	openProjectFile: (id: string, relativePath: string) => typedError<null, AppError>(__TAURI_INVOKE("open_project_file", { id, relativePath })),
	/**
	 *  プロジェクト内のファイルを、ファイルマネージャーでフォルダを開いて選択状態で表示する（設計書 4.7）。
	 *  相対パスは `open_project_file` と同じ検証（`resolve_in_project`）を通し、プロジェクト外
	 *  （`..`・絶対パス・シンボリックリンク経由）は表示しない。画面（JS）には opener の権限を与えず、
	 *  Rust 側の API だけを検証の後に呼ぶ。読み取りのみのため直列キューは通さない。
	 */
	revealProjectFile: (id: string, relativePath: string) => typedError<null, AppError>(__TAURI_INVOKE("reveal_project_file", { id, relativePath })),
	/**  1 ファイルだけを戻した場合の影響（読み取りのみのため直列キューは通さない）。 */
	restoreFilePreview: (id: string, commit: string, path: string) => typedError<RestoreFilePreviewData, AppError>(__TAURI_INVOKE("restore_file_preview", { id, commit, path })),
	/**  指定した保存時点の 1 ファイルだけを戻す。復元点は core-ops が作る。 */
	restoreFile: (id: string, commit: string, path: string, saveMemo: string | null) => typedError<RestoreFileResult, AppError>(__TAURI_INVOKE("restore_file", { id, commit, path, saveMemo })),
	/**  元に戻すの取り消し。`restore_point` は復元点の ref 名（`refs/hikae/` 配下）または完全な OID。 */
	undoRestore: (id: string, restorePoint: string) => typedError<null, AppError>(__TAURI_INVOKE("undo_restore", { id, restorePoint })),
	/**
	 *  新規（未追跡）ファイル 1 件を「元に戻す（作成しない）」。ファイルは OS のごみ箱へ移す。
	 * 
	 *  安全上の不変条件 6 の唯一の例外。復元点（自動保存）にファイルの内容が入っていることを確かめて
	 *  から移し、大きすぎて復元点に入らないファイル・追跡済みのファイル・フォルダ・リンク・プロジェクト外は
	 *  拒否する（core-ops の `discard_new_file`）。直列キュー（不変条件 7）とジャーナルを通す。
	 *  戻り値の `undo_token` は `undo_restore` に渡すと、この操作の前の状態に戻せる。
	 */
	discardNewFile: (id: string, path: string) => typedError<DiscardNewFileResult, AppError>(__TAURI_INVOKE("discard_new_file", { id, path })),
	/**
	 *  プロジェクトフォルダ全体のファイル一覧（保存対象のみ。読み取りのみのため直列キューは通さない）。
	 *  上限（1 万件）を超えたら打ち切り、`truncated` を立てる。
	 */
	listProjectTree: (id: string) => typedError<ProjectTreeData, AppError>(__TAURI_INVOKE("list_project_tree", { id })),
	/**  変更のぶつかり解消を中断し、取り込む前の状態に戻す。 */
	abortMerge: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("abort_merge", { id })),
	/**
	 *  外部のファイル・フォルダをプロジェクトへコピーする（保存はしない。設計書 4.7）。
	 * 
	 *  - `dest_subdir` が空ならプロジェクト直下。ツリー表示のフォルダ行へのドロップでは、そのフォルダ
	 *  - 同名があるときは `on_conflict` に従う。`ask`（既定）で同名があれば、**何も書かずに**
	 *    `needs_decision`（確認が必要な同名のファイル）を返す。画面が選択を `decisions` に添えて呼び直す
	 *  - 置き換えは、復元点に既存の内容が入っていることを確かめられたときだけ行う（できなければ別名で残す）。
	 *    置き換えたときは `undo_token`（`undo_restore` に渡すと、置き換え前の内容に戻る）を返す
	 *  - フォルダは中のファイルを再帰的にコピーする（上限: ファイル 1,000 件・階層 20。超えるときは
	 *    何もコピーせずエラー）。リンクはたどらず、隠しファイルと OS の一時ファイルは飛ばす
	 *  - 警告の閾値は設定 `large_file_warn_mb`（プロジェクト別の上書きを含む）。100MB 超は固定で追加しない
	 */
	addFiles: (id: string, sourcePaths: string[], destSubdir: string, onConflict: AddConflictPolicyData, decisions: AddConflictDecisionData[]) => typedError<AddFilesResult, AppError>(__TAURI_INVOKE("add_files", { id, sourcePaths, destSubdir, onConflict, decisions })),
	/**
	 *  選んだフォルダが広すぎるかを、登録の前に確かめる（フォルダ選択後の注意に使う）。
	 *  広すぎるときは理由の種類、問題なければ null。読み取りのみ。
	 */
	checkProjectFolder: (path: string) => typedError<"home" | "drive-root" | "standard-folder" | "system-folder" | null, AppError>(__TAURI_INVOKE("check_project_folder", { path })),
	/**
	 *  フォルダが見つからないプロジェクトの登録パスを付け替える。
	 *  付け替え先が同じプロジェクトと確認できた場合のみ更新し、ファイルは一切変更しない。
	 */
	relocateProject: (id: string, newPath: string) => typedError<ProjectInfo, AppError>(__TAURI_INVOKE("relocate_project", { id, newPath })),
	/**  保存時点で変更されたファイルの一覧（変更の種類つき、読み取りのみ）。 */
	listPointChanges: (id: string, commit: string) => typedError<PointChangeItem[], AppError>(__TAURI_INVOKE("list_point_changes", { id, commit })),
	/**
	 *  過去の版のファイルを開く（設計書 4.7）。
	 * 
	 *  指定時点の内容をアプリ専用の一時フォルダへ書き出して読み取り専用にし、既定のアプリで開く。
	 *  プロジェクトのファイルとリポジトリは変更しない（読み取りのみのため直列キューは通さない）。
	 *  パスは `..`・絶対パス・`.git` 配下を拒否する。
	 */
	openFileAt: (id: string, commit: string, relativePath: string) => typedError<null, AppError>(__TAURI_INVOKE("open_file_at", { id, commit, relativePath })),
	/**
	 *  中断された操作（E15）の直前の復元点へ、作業フォルダを戻す。
	 * 
	 *  対象は保存・取り込み系（`save` / `pull` / `push` / `resolve`）。復元点は
	 *  `refs/hikae/backup/` の、その操作が始まった後に作られた最新のもの。戻す前にいまの状態の
	 *  復元点を作り、`restore --source` で戻す（`reset --hard` / `checkout -f` は使わない）。
	 *  実行は直列キューとジャーナルを通す。復元点が見つからなければ何も変更せずエラーを返し、
	 *  中断の印は残る。成功すると中断の印を解除する。
	 */
	recoverInterrupted: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("recover_interrupted", { id })),
	/**  ログイン状態を返す。 */
	getSession: () => typedError<SessionInfo, AppError>(__TAURI_INVOKE("get_session")),
	/**  ログインを始める（Device Flow）。確認コードと確認ページの URL を返す。 */
	startLogin: () => typedError<LoginStart, AppError>(__TAURI_INVOKE("start_login")),
	/**  ユーザーが GitHub で許可するまで待つ。長時間かかるため async のまま待機し、`cancel_login` で中断できる。 */
	waitLogin: () => typedError<LoginOutcome, AppError>(__TAURI_INVOKE("wait_login")),
	/**  進行中のログインを中断する。待機中の `wait_login` は `canceled` で戻る。 */
	cancelLogin: () => __TAURI_INVOKE<void>("cancel_login"),
	/**
	 *  ログインの確認ページ（https://github.com/login/device）を既定のブラウザで開く。
	 *  任意の URL は受け取らない。開くのは進行中のログインが保持している確認 URL だけで、
	 *  ホストとパスが固定の確認ページと完全一致する場合に限る。
	 */
	openLoginPage: () => typedError<null, AppError>(__TAURI_INVOKE("open_login_page")),
	/**  ログアウトする。キーチェーンのトークンを削除する（GitHub 側の許可の取り消しは行わない）。 */
	logout: () => typedError<null, AppError>(__TAURI_INVOKE("logout")),
	/**  保存先（個人 + 所属 Organization）の一覧。 */
	listOwners: () => typedError<OwnerInfo[], AppError>(__TAURI_INVOKE("list_owners")),
	/**  取得できるリポジトリの一覧（`query` を含む `owner/name` に絞り込む）。 */
	listRemoteProjects: (query: string) => typedError<RemoteProjectList, AppError>(__TAURI_INVOKE("list_remote_projects", { query })),
	/**
	 *  GitHub のリポジトリをこの PC のフォルダへ取得し、プロジェクトとして登録する。
	 * 
	 *  - `repo` は `owner/name`。URL は常に `https://github.com/...` に固定し、任意の URL は受け付けない
	 *  - `path` は取得先のフォルダ。存在しないか空である必要がある（空でなければ拒否し、中身には触れない）
	 *  - 認証は credential helper 経由（トークンを URL や引数に載せない）
	 *  - 新しいフォルダを作るだけで既存のファイルを変更しないため、復元点は作らない
	 */
	cloneProject: (id: string, repo: string, path: string, displayName: string | null) => typedError<ProjectInfo, AppError>(__TAURI_INVOKE("clone_project", { id, repo, path, displayName })),
	/**
	 *  ローカルだけのプロジェクトを、GitHub 上の新しいリポジトリに接続する。
	 * 
	 *  新規作成のときと同じ流れだが、初回の保存は作らない（保存は利用者が行う）。すでにある保存は
	 *  初回のアップロードで上がる。同名のリポジトリが GitHub にすでにある場合は、空で書き込めるものだけ
	 *  `existing_empty_repository` で接続を提案し（何も作られず、ローカルも変更されない）、承認されたら
	 *  `adopt_existing: true` で呼び直す。空でないものは `remote_name_taken`（接続しない）。
	 */
	connectRemote: (id: string, request: RemoteRequest) => typedError<RemoteConnectResult, AppError>(__TAURI_INVOKE("connect_remote", { id, request })),
	/**  設定を取得する。`project_id` を指定すると、そのプロジェクトの上書きを反映した設定を返す。 */
	getSettings: (projectId: string | null) => typedError<SettingsView, AppError>(__TAURI_INVOKE("get_settings", { projectId })),
	/**
	 *  設定を更新する。指定した項目だけを書き換え、更新後の設定を返す。
	 *  `project_id` を指定するとそのプロジェクトの上書きとして保存する（上書きできない項目は拒否）。
	 */
	updateSettings: (projectId: string | null, patch: SettingsPatch_Deserialize) => typedError<SettingsView, AppError>(__TAURI_INVOKE("update_settings", { projectId, patch })),
	/**  初回設定の完了を記録する。 */
	completeOnboarding: () => typedError<null, AppError>(__TAURI_INVOKE("complete_onboarding")),
};

/** Events */
export const events = {
	cloneProgress: makeEvent<CloneProgress>("clone-progress"),
	filesChanged: makeEvent<FilesChanged>("files-changed"),
	needsAttention: makeEvent<NeedsAttention>("needs-attention"),
	opFinished: makeEvent<OpFinished>("op-finished"),
	opProgress: makeEvent<OpProgress>("op-progress"),
	statusChanged: makeEvent<StatusChanged>("status-changed"),
	syncStateChanged: makeEvent<SyncStateChanged>("sync-state-changed"),
};

/* Types */
/**  同名のファイル 1 件についての選択 */
export type AddConflictActionData = "replace" | "keep-both" | 
/**  このファイルは追加しない */
"skip";

/**  追加先のパスごとの選択（方針より優先する） */
export type AddConflictDecisionData = {
	/**  追加先のパス（プロジェクトからの相対パス） */
	path: string,
	action: AddConflictActionData,
};

/**  同名のファイルがあるときの方針 */
export type AddConflictPolicyData = 
/**  同名があれば、何も書かずに確認が必要な一覧を返す */
"ask" | 
/**  同名があれば、別名にして両方残す */
"keep-both" | 
/**  同名があれば置き換える（復元点に控えを残せないものは別名にする） */
"replace";

/**  ファイル追加の結果 */
export type AddFilesResult = {
	added: AddedFileItem[],
	rejected: RejectedFileItem[],
	/**  リンク・隠しファイル・一時ファイルとして飛ばしたもの */
	skipped: SkippedFileItem[],
	/**  空でないとき、同名のファイルがあって何も書かずに返した。選択を添えて呼び直す */
	needs_decision: NameConflictItem[],
	/**  置き換えたときの取り消し用の復元点（`undo_restore` に渡す）。置き換えが無ければ null */
	undo_token: string | null,
};

/**  プロジェクト追加の結果 */
export type AddProjectResult = {
	/**  保存先の作成を頼まれたときだけ入る */
	remote: RemoteConnectResult | null,
};

/**  追加しなかった理由 */
export type AddRejectKind = 
/**  100MB を超えるため追加できない */
"too-large" | 
/**  通常のファイルではない */
"not-a-file" | 
/**  読み取れない、またはコピーに失敗した */
"unreadable" | 
/**  置き換え先のファイルが他のアプリで使用中 */
"in-use";

/**  追加できたファイル */
export type AddedFileItem = {
	/**  プロジェクトからの相対パス */
	path: string,
	/**  同名があったため別名にした */
	renamed: boolean,
	/**  大きいファイル（警告閾値 `large_file_warn_mb` を超える）。アップロードに時間がかかることを知らせる */
	large: boolean,
	/**  同名の既存ファイルを置き換えた（置き換え前の内容は復元点に残っている） */
	replaced: boolean,
	/**  置き換えを選ばれたが、安全に置き換えられなかったため別名にした */
	replace_refused: boolean,
};

/**  元に戻した後の保存の結果（設計書 4.2 手順 5） */
export type AfterRestoreSaveKind = 
/**  保存しなかった（設定がオフ、またはメモが渡されなかった） */
"not-requested" | 
/**  保存した */
"saved" | 
/**  保存する変更が無かった */
"nothing-to-save" | 
/**  大きいファイルの確認が必要なため保存しなかった（戻す操作は成功。画面の通常の保存の流れに任せる） */
"needs-size-decision" | 
/**  保存に失敗した（戻す操作は成功。未保存の変更として残っている） */
"failed";

/**  AI モデルの指定方法 */
export type AiModelSource = "catalog" | "custom-gguf";

/**  AI の実行方式 */
export type AiRunner = "builtin" | "ollama";

/**  AI に渡す範囲 */
export type AiScope = "file-names" | "text-diff" | "with-images";

/**
 *  何が起きたか、データは無事か、次の行動を含むエラー型。
 * 
 *  画面は `code` と `params` から言語リソース（i18n キー）で文言を組み立てる。
 *  `what_happened` / `data_is_safe` / `next_action`（日本語）は、対応する文言が無い場合の
 *  フォールバックとして残す。`params` にはファイル名などの表示用の値だけを入れ、
 *  トークンや認証情報、git の標準エラー出力（`technical_info` に入れる）は入れない。
 * 
 *  コード一覧（`OpsError` / 認証エラーと 1 対 1）:
 * 
 *  - 操作: `conflict`（params: `count`）、`git_failed`、`git_timeout`、`safety_check_failed`、
 *    `io_error`、`file_in_use`（params: `file`。特定できたときのみ）、`invalid_input`、
 *    `restore_point_not_found`、`unexpected`
 *  - 新規ファイルの「元に戻す（作成しない）」: `discard_not_untracked`（保存の対象になっている）、
 *    `discard_not_a_file`（フォルダ・リンク・見つからない）、`discard_file_too_large`（復元点に
 *    入らない大きさ）、`discard_not_backed_up`（復元点に内容を確認できない）、`trash_failed`
 *    （ごみ箱へ移せない）。どれも params は `file`（ファイル名のみ）で、ファイルは削除していない
 *  - ファイル・フォルダの追加: `add_too_many_files`（フォルダの中が 1,000 件を超える）、
 *    `add_folder_too_deep`（階層が 20 を超える）。params は `limit`。何もコピーしていない
 *  - ファイルを開く: `file_not_found`、`file_unreadable`、`outside_project`
 *  - 認証・GitHub: `not_logged_in`（E01）、`github_forbidden`（E02）、`github_rate_limited`、
 *    `network_unavailable`（E03）、`github_unavailable`（E04）、`login_not_configured`、
 *    `keychain_error`、`login_not_in_progress`、`login_page_unexpected`、`browser_open_failed`、
 *    `github_error`
 *  - 保存先の作成・接続: `remote_name_taken`（同名のリポジトリが既にある）、`remote_name_invalid`、
 *    `remote_owner_invalid`、`remote_public_not_confirmed`、`remote_already_connected`、
 *    `project_folder_missing`、`remote_conflict`（`origin` がすでに別の場所を指している。作成の前の
 *    検査）、`remote_not_writable`（`.git/config` に書き込めない。作成の前の検査）、
 *    `remote_orphaned`（GitHub 上に空の保存先ができたが、プロジェクトに接続できなかった。params:
 *    `name` = 作成済みの `owner/name`）
 *    （権限不足は `github_forbidden`（E02）、通信できないは `network_unavailable`（E03））
 *  - 取得（clone）: `clone_invalid_repo`、`clone_invalid_destination`、`destination_not_empty`、
 *    `destination_not_a_folder`、`destination_unreadable`、`remote_not_found`（E16）、
 *    `clone_failed`、`clone_timeout`、`clone_register_failed`
 *  - プロジェクト: `project_not_found`、`project_already_registered`、`folder_already_registered`、
 *    `project_folder_too_broad`（ホームフォルダ・ドライブのルート・標準フォルダ・システムフォルダ）、
 *    `project_list_failed`、`project_register_failed`、`project_remove_failed`、
 *    `relocate_not_a_project`、`relocate_different_project`、`relocate_cannot_verify`、
 *    `relocate_failed`
 *  - 内部: `database_error`、`task_failed`、`lock_failed`、`settings_io_failed`、
 *    `invalid_settings`、`status_failed`、`history_failed`、`diff_failed`、
 *    `change_list_failed`、`conflict_list_failed`、`preview_failed`、`open_failed`
 * 
 *  大きいファイル（E07 / E08）はエラーではなく構造化した結果（`SizeCheckResult`）で返すため、
 *  ここにはコードを置かない。
 */
export type AppError = {
	/**  機械可読なエラーコード（上の一覧）。画面の文言の選択に使う */
	code: string,
	/**  文言に差し込む値（キーと値の組。ファイル名など） */
	params: ([string, string])[],
	/**  何が起きたか（ユーザー向けの平易な説明） */
	what_happened: string,
	/**  データは無事か（1文で） */
	data_is_safe: string,
	/**  次の行動（ボタンラベルと説明） */
	next_action: string,
	/**  技術情報（Git エラー原文など。秘密情報は除外） */
	technical_info: string | null,
};

/**  全体設定（またはプロジェクト別の上書きを反映した、実際に使う設定） */
export type AppSettings = {
	/**  初回設定（ログインと保存先の案内）を完了したか */
	onboarded: boolean,
	/**  起動時に取り込む */
	pull_on_startup: boolean,
	/**  定期的に取り込む間隔（分）。0 はオフ。1〜1440 の任意の値（画面の選択肢は 0 / 5 / 15 / 60 とカスタム） */
	pull_interval_minutes: number,
	/**  取り込む前に未保存の変更を保存する（false は「確認する」） */
	save_before_pull: boolean,
	/**  ぶつかり発生時の動作 */
	conflict_mode: ConflictMode,
	/**  保存時に自動アップロードする */
	auto_push_after_save: boolean,
	/**  アップロード待ちの通知間隔（時間）。0 はオフ。選択肢は 0 / 1 / 24 */
	push_reminder_hours: number,
	/**  ファイル監視による自動保存 */
	auto_snapshot_enabled: boolean,
	/**  最後の変更からこの秒数だけ静止してから記録する。10〜3600 の任意の値（画面の選択肢は 30 / 120 / 600 とカスタム） */
	auto_snapshot_delay_secs: number,
	/**  自動保存の保持期間（日）。7〜730 の任意の値（画面の選択肢は 30 / 90 / 365 とカスタム） */
	snapshot_retention_days: number,
	/**  メモの自動提案の方式 */
	memo_suggestion: MemoSuggestion,
	/**  元に戻した後に自動で保存する */
	auto_save_after_restore: boolean,
	/**  大きいファイルの警告閾値（MB）。1〜100 の任意の値（画面の選択肢は 25 / 50 / 100 とカスタム） */
	large_file_warn_mb: number,
	/**  自動保存をタイムラインに表示するか */
	show_snapshots_in_timeline: TimelineSnapshots,
	/**  「開く」の既定動作 */
	open_action: OpenAction,
	/**  実行方式 */
	ai_runner: AiRunner,
	/**  使用モデルの識別子。空は未インストール */
	ai_model: string,
	/**  AI に渡す範囲 */
	ai_scope: AiScope,
	/**  git 実行ファイル */
	git_executable: GitExecutable,
	/**  技術情報をエラーに表示する */
	show_technical_info: boolean,
	/**  新規リポジトリの既定の公開範囲 */
	default_visibility: DefaultVisibility,
	/**  自動保存の容量上限（プロジェクトサイズの倍数）。0 は上限なし。選択肢は 0 / 1 / 2 / 5。Phase 2 */
	snapshot_size_cap_x: number,
	/**  AI モデルの指定方法。Phase 2 */
	ai_model_source: AiModelSource,
	/**  任意の GGUF ファイルのパス（`ai_model_source` が `custom-gguf` のとき）。Phase 2 */
	ai_custom_gguf_path: string,
	/**  作業コピー機能を表示する。Phase 3 */
	work_copy_enabled: boolean,
	/**  拡張機能の開発者モード（署名なしの手動導入）。Phase 3 */
	extension_dev_mode: boolean,
	/**  拡張機能の追加索引の URL。空は公式のみ。Phase 4 */
	extension_index_urls: string[],
	/**  Git LFS を有効にする。Phase 4 */
	git_lfs: boolean,
	/**  用語の表示 */
	term_display: TermDisplay,
};

/**  ユーザーの対応が必要な理由 */
export type AttentionReason = 
/**  変更のぶつかりがある */
"conflict" | 
/**  再認証が必要 */
"auth" | 
/**  未保存の変更があるため、自動の取り込みを見送った */
"unsaved-changes" | 
/**  取り込み前の自動保存に大きいファイルがあるため、自動の取り込みを見送った（E07 / E08） */
"large-files" | 
/**  前回のアプリ終了で、途中で止まった操作が見つかった（E15） */
"interrupted-operation" | 
/**
 *  登録したフォルダが見つからない・フォルダでない・リポジトリでない（E11）。自動の取り込み・
 *  アップロードは、フォルダが戻るまで見送る
 */
"folder-missing";

/**  広すぎるフォルダの種類 */
export type BroadFolderKind = "home" | "drive-root" | "standard-folder" | "system-folder";

/**  変更ファイル */
export type ChangeFile = {
	path: string,
	kind: ChangeKind,
	/**  変更のぶつかり中のファイルか */
	conflicted: boolean,
	/**
	 *  一度も保存されておらず、インデックスにも入っていない新規ファイルか。
	 *  「元に戻す（作成しない）」を出せるのはこのファイルだけ
	 */
	untracked: boolean,
};

export type ChangeKind = "modified" | "added" | "deleted" | "renamed";

/**  GitHub から取得する処理の段階 */
export type ClonePhase = 
/**  取得先や認証の確認中 */
"preparing" | 
/**  ファイルをダウンロード中（git の実行中。割合は取得できない） */
"downloading" | 
/**  ダウンロード後の仕上げ（登録）中 */
"finishing" | 
/**  完了した */
"done" | 
/**  失敗した（エラーは呼び出しの戻り値で返す） */
"failed";

/**  GitHub からの取得の進行状況。実行中のプロジェクトは一覧にまだ無いため、呼び出し時に渡した ID で識別する。 */
export type CloneProgress = {
	project_id: string,
	phase: ClonePhase,
};

export type ConflictChoice = "mine" | "theirs";

/**  競合ファイル */
export type ConflictItem = {
	path: string,
	kind: ConflictKind,
	/**  この PC 側の最終保存日時（Unix 秒）。不明なら null */
	this_saved_at: number | null,
	/**  クラウド側の最終保存日時（Unix 秒）。不明なら null */
	cloud_saved_at: number | null,
	/**  この PC 側の最終保存を作った PC の名前。記録が無ければ null */
	this_pc_name: string | null,
	/**  クラウド側の最終保存を作った PC の名前。記録が無ければ null */
	cloud_pc_name: string | null,
};

export type ConflictKind = "both-modified" | "both-added" | "deleted-by-us" | "deleted-by-them" | "both-deleted";

/**  ぶつかり発生時の動作 */
export type ConflictMode = 
/**  すぐ解消画面を開く */
"show-dialog" | 
/**  通知だけ出す */
"notify-only";

/**  新規リポジトリの既定の公開範囲 */
export type DefaultVisibility = "private" | "public";

/**  差分行 */
export type DiffLine = {
	kind: DiffLineKind,
	content: string,
};

export type DiffLineKind = "added" | "removed" | "context";

/**  差分の取得結果 */
export type DiffResult = {
	kind: DiffResultKind,
	/**  差分の行。`kind` が `lines` のときだけ入る */
	lines: DiffLine[],
	/**  ファイルサイズ（バイト）。`binary` と `too-large` のときだけ入る */
	size: number | null,
	/**  最終更新（Unix 秒）。`binary` と `too-large` のとき、取得できれば入る */
	modified_at: number | null,
};

/**  差分の取得結果の種類 */
export type DiffResultKind = 
/**  差分の行（`lines`）。新規ファイルは全行が追加。空なら差分なし */
"lines" | 
/**  内容が空の新規ファイル */
"new-file-empty" | 
/**  本文を出せない新規ファイル（バイナリ・リンク）。`size` と `modified_at` だけを持つ */
"binary" | 
/**  大きすぎて本文を省略した新規ファイル。`size` と `modified_at` だけを持つ */
"too-large";

/**  新規ファイルを「元に戻す（作成しない）」結果 */
export type DiscardNewFileResult = {
	/**  取り消しに使う復元点（`undo_restore` の `restore_point` に渡す） */
	undo_token: string | null,
};

/**  保存時点のファイル（S3「この時点の全ファイルを見る」用） */
export type FileEntry = {
	/**  リポジトリ相対パス */
	path: string,
	/**  ファイルサイズ（バイト） */
	size: number | null,
};

/**
 *  プロジェクトのフォルダでファイルが変わった（ファイル監視。保存の対象になりうる変更だけ）。
 *  UI は変更一覧のキャッシュだけを無効化して取り直す（重い再取得を避けるため `status_changed` とは分ける）。
 */
export type FilesChanged = {
	project_id: string,
};

/**  git 実行ファイルの種類 */
export type GitExecutable = "bundled" | "system";

/**  履歴アイテム */
export type HistoryItem = {
	commit: string,
	timestamp: string,
	message: string,
	changed_files_count: number,
	is_snapshot: boolean,
	/**  この保存を作った PC の名前。記録が無ければ null。`message` には含まれない */
	pc_name: string | null,
	/**  クラウドに上がっている保存か。自動保存と、クラウドの保管場所が無い・まだ何も上げていないときは false */
	cloud_synced: boolean,
};

/**  大きいファイル */
export type LargeFileItem = {
	/**  プロジェクトからの相対パス */
	path: string,
	/**  ファイルサイズ（バイト） */
	size: number | null,
};

/**  ログインの結末 */
export type LoginOutcome = 
/**  ログインできた */
"succeeded" | 
/**  GitHub の画面で拒否された */
"denied" | 
/**  有効期限が切れた */
"expired" | 
/**  キャンセルした */
"canceled";

/**  画面に出すログイン手順（device_code は含まない） */
export type LoginStart = {
	/**  GitHub の画面で入力するコード */
	user_code: string,
	/**  コードを入力するページの URL */
	verification_uri: string,
	/**  有効期限（秒） */
	expires_in: number,
	/**  ポーリング間隔（秒） */
	interval: number,
};

/**  メモの自動提案の方式 */
export type MemoSuggestion = 
/**  ルールのみ */
"rules" | 
/**  AI を使う */
"ai";

/**  確認が必要な同名のファイル */
export type NameConflictItem = {
	/**  追加先のパス（プロジェクトからの相対パス） */
	path: string,
	/**  置き換えを選べるか。復元点に控えを残せない大きさのものは false（別名のみ） */
	can_replace: boolean,
};

/**  ユーザーの対応が必要になった */
export type NeedsAttention = {
	project_id: string,
	reason: AttentionReason,
};

/**  状態変更操作が終わった */
export type OpFinished = {
	project_id: string,
	operation: string,
	trigger: OpTrigger,
	ok: boolean,
	/**  結果の要約（`merged` / `up-to-date` / 失敗の種類など。エラー本文は含まない） */
	outcome: string,
};

/**  状態変更操作を開始した */
export type OpProgress = {
	project_id: string,
	/**  `save` / `restore` / `pull` / `push` / `resolve` */
	operation: string,
	trigger: OpTrigger,
};

/**  操作の起動元 */
export type OpTrigger = 
/**  ユーザーの操作 */
"manual" | 
/**  スケジューラによる自動実行 */
"auto";

/**  「開く」の既定動作 */
export type OpenAction = "default-app" | "vs-code";

/**  保存先に作れない理由 */
export type OwnerBlockReason = 
/**  Organization への参加が承認待ち */
"pending-invitation" | 
/**  Organization の設定でメンバーによる作成が許可されていない */
"members-cannot-create" | 
/**  Organization の情報を確認できない（メンバーでない、またはアプリの利用が許可されていない） */
"no-access";

/**  保存先（個人または Organization） */
export type OwnerInfo = {
	/**  GitHub のログイン名。`RemoteProjectInfo.owner_id` と一致する */
	id: string,
	name: string,
	kind: OwnerKindData,
	avatar_url: string | null,
	/**  新しく作れるか。false のときは灰色表示にして `reason` を説明する */
	can_create: boolean,
	reason: OwnerBlockReason | null,
};

/**  保存先の種類 */
export type OwnerKindData = "personal" | "org";

/**  保存時点で変更されたファイル */
export type PointChangeItem = {
	path: string,
	/**  名前変更の場合の元のパス */
	old_path: string | null,
	kind: PointChangeKindData,
};

/**  保存時点で変更されたファイルの種類 */
export type PointChangeKindData = "added" | "modified" | "deleted" | "renamed";

/**  プロジェクトフォルダ内のファイル 1 件 */
export type ProjectFileItem = {
	/**  プロジェクト内の相対パス（`/` 区切り） */
	path: string,
	/**  ファイルサイズ（バイト）。作業フォルダに無い（削除された）ときは null */
	size: number | null,
	/**  最終更新（Unix 秒）。取得できなければ null */
	modified_at: number | null,
	/**  未保存の変更の種類。変更が無ければ null */
	change: ChangeKind | null,
	/**  変更のぶつかり中のファイルか */
	conflicted: boolean,
};

/**  プロジェクト情報 */
export type ProjectInfo = {
	id: string,
	display_name: string,
	path: string,
	remote_url: string | null,
	owner: string,
	last_viewed_at: string,
	/**  登録したフォルダが見つからない・フォルダでない・リポジトリでない（E11）。true のとき git は実行していない */
	folder_missing: boolean,
	/**
	 *  クラウドに上がっている最新の保存の日時（ISO 8601）。保存先が無い、まだ何も上げていない、
	 *  フォルダが見つからないときは null
	 */
	last_uploaded_at: string | null,
	/**  最新の手動の保存の日時（ISO 8601）。自動保存は含めない。まだ保存が無い、フォルダが見つからないときは null */
	last_saved_at: string | null,
};

/**  プロジェクトフォルダ全体のファイル一覧 */
export type ProjectTreeData = {
	entries: ProjectFileItem[],
	/**  上限を超えたため、一部のみを含む */
	truncated: boolean,
	/**  一覧に含めるファイル数の上限 */
	limit: number,
};

/**  取り込み結果 */
export type PullResult = {
	outcome: string,
	conflicts: ConflictItem[],
	/**  取り込み前の自動保存に大きいファイルがあり、何も変更せず見送った場合の内容（E07 / E08）。なければ null */
	size_check: SizeCheckResult | null,
	/**
	 *  未保存の変更があり、取り込む前の保存の確認を求める場合（結果 `needs-save-confirmation`）の
	 *  未保存のファイルの件数（E06）。なければ null
	 */
	unsaved_count: number | null,
};

/**  アップロード結果 */
export type PushResult = {
	outcome: string,
	/**  取り込み前の自動保存に大きいファイルがあり、何も変更せず見送った場合の内容。なければ null */
	size_check: SizeCheckResult | null,
};

/**  追加しなかったファイル */
export type RejectedFileItem = {
	/**  元のファイル名。フォルダの中のものは、ドロップしたフォルダからの相対パス */
	name: string,
	reason: AddRejectKind,
	/**  `too-large` のときの元のサイズ（バイト） */
	size: number | null,
};

/**  保存先の接続の結果 */
export type RemoteConnectResult = {
	/**  GitHub 上に作ったリポジトリ（`owner/name`）。作れなかったときは null */
	repository: string | null,
	/**  保存先を設定できた（以降は取り込み・アップロードの対象になる） */
	connected: boolean,
	/**  初回のアップロードまで完了した（アップロードするものが無かったときは false） */
	uploaded: boolean,
	/**
	 *  初回の保存に大きいファイルがあり、保存を見送った場合の内容（E07 / E08）。なければ null
	 * 
	 *  `connected` が false のときは、GitHub には何も作っておらず、ローカルも変更していない
	 *  （作成の前の検査で見つかった。画面は 2 択を出し、選択を保存に反映してから接続をやり直す）
	 */
	size_check: SizeCheckResult | null,
	/**
	 *  同じ名前の空の保存先（`owner/name`）が GitHub にすでにあり、新しくは作らなかった場合の名前。
	 *  何も作らず、ローカルも変更していない。画面が「ここに接続しますか」と確認し、承認されたら
	 *  `adopt_existing` を true にして接続をやり直す。なければ null
	 */
	existing_empty_repository: string | null,
	/**  途中で失敗した場合の 3 要素のエラー（E02 / E03 など）。ローカルのファイルは無事 */
	error: AppError | null,
};

/**  取得できるリポジトリ */
export type RemoteProjectInfo = {
	/**  `owner/name`。`clone_project` の `repo` に渡す */
	id: string,
	name: string,
	/**  所有者のログイン名（`OwnerInfo.id`） */
	owner_id: string,
	private: boolean,
	/**  最終更新日時（RFC3339） */
	updated_at: string | null,
};

/**  取得できるリポジトリの一覧 */
export type RemoteProjectList = {
	/**  オーナーごとにまとまった並び（個人が先、Organization は名前順。各オーナー内も名前順） */
	projects: RemoteProjectInfo[],
	/**  件数が多く、一部しか取得していない */
	truncated: boolean,
};

/**  保存先（GitHub 上のリポジトリ）の作成の要求 */
export type RemoteRequest = {
	/**  保存先（個人のログイン名、または Organization 名）。`list_owners` の `id` */
	owner: string,
	/**
	 *  リポジトリ名。省略時はプロジェクト名から作る（英数字・`-`・`_`・`.` のみ。日本語の名前などは
	 *  `hikae-<識別子>` にする）
	 */
	name: string | null,
	/**  非公開にする（既定の選択肢） */
	private: boolean,
	/**  公開にすることの警告を確認した。`private` が false のとき、これが true でなければ拒否する */
	public_confirmed: boolean,
	/**
	 *  同名の「空の」保存先がすでにあるとき、新しく作らずにそこへ接続する（利用者が確認したあとだけ true）。
	 *  空でない保存先、書き込めない保存先には接続しない（バックエンドが改めて確かめる）
	 */
	adopt_existing: boolean,
};

/**  全体を元に戻した結果 */
export type RestoreAllResult = {
	/**  取り消しに使う復元点（`undo_restore` の `restore_point` に渡す） */
	undo_token: string | null,
	/**  戻した後の保存の結果 */
	save: AfterRestoreSaveKind,
};

/**  1 ファイルを戻す影響の種類 */
export type RestoreFileKindData = 
/**  いまのファイルを指定時点の内容で置き換える */
"overwrite" | 
/**  いまは無いファイルを作り直す */
"recreate" | 
/**  すでに同じ内容 */
"unchanged" | 
/**  指定時点には存在しない（戻せない） */
"not-in-that-point";

/**  1 ファイルを戻す操作のプレビュー */
export type RestoreFilePreviewData = {
	kind: RestoreFileKindData,
	/**  いまのファイルのサイズ（バイト）。無ければ null */
	size_now: number | null,
	/**  指定時点のファイルのサイズ（バイト）。存在しなければ null */
	size_then: number | null,
};

/**  1 ファイルを戻した結果 */
export type RestoreFileResult = {
	outcome: RestoreFileResultKind,
	/**  取り消しに使う復元点（`undo_restore` の `restore_point` に渡す）。戻していなければ null */
	undo_token: string | null,
	/**  戻した後の保存の結果 */
	save: AfterRestoreSaveKind,
};

/**  1 ファイルを戻した結果の種類 */
export type RestoreFileResultKind = 
/**  戻した */
"restored" | 
/**  指定時点に無いため何も変更しなかった */
"not-in-that-point" | 
/**  同名の保存対象外ファイルを上書きしてしまうため何も変更しなかった */
"ignored-file-in-the-way";

/**  元に戻すプレビュー */
export type RestorePreviewData = {
	modified: string[],
	deleted: string[],
	created: string[],
};

/**  保存結果 */
export type SaveResult = {
	commit: string | null,
	message: string | null,
	/**  大きいファイルがあり、保存しなかった場合の内容（E07 / E08）。なければ null */
	size_check: SizeCheckResult | null,
};

/**  大きいファイルについての選択。既定（何も選ばない）は、問題のあるファイルがあれば保存しない。 */
export type SaveSizeChoice = {
	/**  警告（E08）のファイルをそのまま保存する */
	accept_warned: boolean,
	/**
	 *  保存対象から外すファイル（検査で見つかったファイルのパスのみ）。.gitignore に追記され、
	 *  ファイル自体は消えない
	 */
	exclude: string[],
};

/**  現在のログイン状態。トークンは含めない。 */
export type SessionInfo = {
	/**  ログイン済みか（オフラインでユーザー情報を確認できない場合も true） */
	logged_in: boolean,
	/**  トークンが失効・取り消しされており、もう一度ログインが必要（E01） */
	reauth_required: boolean,
	/**  初回設定を完了したか */
	onboarded: boolean,
	/**  ユーザー情報。未ログイン、またはオフラインで確認できないときは null */
	user: SessionUser | null,
};

/**  ログイン中の GitHub ユーザー（表示用） */
export type SessionUser = {
	login: string,
	avatar_url: string | null,
};

/**  設定の更新内容。指定した項目だけを書き換える。 */
export type SettingsPatch = SettingsPatch_Serialize | SettingsPatch_Deserialize;

/**  設定の更新内容。指定した項目だけを書き換える。 */
export type SettingsPatch_Deserialize = {
	/**  初回設定（ログインと保存先の案内）を完了したか */
	onboarded?: boolean | null,
	/**  起動時に取り込む */
	pull_on_startup?: boolean | null,
	/**  定期的に取り込む間隔（分）。0 はオフ。1〜1440 の任意の値（画面の選択肢は 0 / 5 / 15 / 60 とカスタム） */
	pull_interval_minutes?: number | null,
	/**  取り込む前に未保存の変更を保存する（false は「確認する」） */
	save_before_pull?: boolean | null,
	/**  ぶつかり発生時の動作 */
	conflict_mode?: ConflictMode | null,
	/**  保存時に自動アップロードする */
	auto_push_after_save?: boolean | null,
	/**  アップロード待ちの通知間隔（時間）。0 はオフ。選択肢は 0 / 1 / 24 */
	push_reminder_hours?: number | null,
	/**  ファイル監視による自動保存 */
	auto_snapshot_enabled?: boolean | null,
	/**  最後の変更からこの秒数だけ静止してから記録する。10〜3600 の任意の値（画面の選択肢は 30 / 120 / 600 とカスタム） */
	auto_snapshot_delay_secs?: number | null,
	/**  自動保存の保持期間（日）。7〜730 の任意の値（画面の選択肢は 30 / 90 / 365 とカスタム） */
	snapshot_retention_days?: number | null,
	/**  メモの自動提案の方式 */
	memo_suggestion?: MemoSuggestion | null,
	/**  元に戻した後に自動で保存する */
	auto_save_after_restore?: boolean | null,
	/**  大きいファイルの警告閾値（MB）。1〜100 の任意の値（画面の選択肢は 25 / 50 / 100 とカスタム） */
	large_file_warn_mb?: number | null,
	/**  自動保存をタイムラインに表示するか */
	show_snapshots_in_timeline?: TimelineSnapshots | null,
	/**  「開く」の既定動作 */
	open_action?: OpenAction | null,
	/**  実行方式 */
	ai_runner?: AiRunner | null,
	/**  使用モデルの識別子。空は未インストール */
	ai_model?: string | null,
	/**  AI に渡す範囲 */
	ai_scope?: AiScope | null,
	/**  git 実行ファイル */
	git_executable?: GitExecutable | null,
	/**  技術情報をエラーに表示する */
	show_technical_info?: boolean | null,
	/**  新規リポジトリの既定の公開範囲 */
	default_visibility?: DefaultVisibility | null,
	/**  自動保存の容量上限（プロジェクトサイズの倍数）。0 は上限なし。選択肢は 0 / 1 / 2 / 5。Phase 2 */
	snapshot_size_cap_x?: number | null,
	/**  AI モデルの指定方法。Phase 2 */
	ai_model_source?: AiModelSource | null,
	/**  任意の GGUF ファイルのパス（`ai_model_source` が `custom-gguf` のとき）。Phase 2 */
	ai_custom_gguf_path?: string | null,
	/**  作業コピー機能を表示する。Phase 3 */
	work_copy_enabled?: boolean | null,
	/**  拡張機能の開発者モード（署名なしの手動導入）。Phase 3 */
	extension_dev_mode?: boolean | null,
	/**  拡張機能の追加索引の URL。空は公式のみ。Phase 4 */
	extension_index_urls?: string[] | null,
	/**  Git LFS を有効にする。Phase 4 */
	git_lfs?: boolean | null,
	/**  用語の表示 */
	term_display?: TermDisplay | null,
};

/**  設定の更新内容。指定した項目だけを書き換える。 */
export type SettingsPatch_Serialize = {
	/**  初回設定（ログインと保存先の案内）を完了したか */
	onboarded?: boolean | null,
	/**  起動時に取り込む */
	pull_on_startup?: boolean | null,
	/**  定期的に取り込む間隔（分）。0 はオフ。1〜1440 の任意の値（画面の選択肢は 0 / 5 / 15 / 60 とカスタム） */
	pull_interval_minutes?: number | null,
	/**  取り込む前に未保存の変更を保存する（false は「確認する」） */
	save_before_pull?: boolean | null,
	/**  ぶつかり発生時の動作 */
	conflict_mode?: ConflictMode | null,
	/**  保存時に自動アップロードする */
	auto_push_after_save?: boolean | null,
	/**  アップロード待ちの通知間隔（時間）。0 はオフ。選択肢は 0 / 1 / 24 */
	push_reminder_hours?: number | null,
	/**  ファイル監視による自動保存 */
	auto_snapshot_enabled?: boolean | null,
	/**  最後の変更からこの秒数だけ静止してから記録する。10〜3600 の任意の値（画面の選択肢は 30 / 120 / 600 とカスタム） */
	auto_snapshot_delay_secs?: number | null,
	/**  自動保存の保持期間（日）。7〜730 の任意の値（画面の選択肢は 30 / 90 / 365 とカスタム） */
	snapshot_retention_days?: number | null,
	/**  メモの自動提案の方式 */
	memo_suggestion?: MemoSuggestion | null,
	/**  元に戻した後に自動で保存する */
	auto_save_after_restore?: boolean | null,
	/**  大きいファイルの警告閾値（MB）。1〜100 の任意の値（画面の選択肢は 25 / 50 / 100 とカスタム） */
	large_file_warn_mb?: number | null,
	/**  自動保存をタイムラインに表示するか */
	show_snapshots_in_timeline?: TimelineSnapshots | null,
	/**  「開く」の既定動作 */
	open_action?: OpenAction | null,
	/**  実行方式 */
	ai_runner?: AiRunner | null,
	/**  使用モデルの識別子。空は未インストール */
	ai_model?: string | null,
	/**  AI に渡す範囲 */
	ai_scope?: AiScope | null,
	/**  git 実行ファイル */
	git_executable?: GitExecutable | null,
	/**  技術情報をエラーに表示する */
	show_technical_info?: boolean | null,
	/**  新規リポジトリの既定の公開範囲 */
	default_visibility?: DefaultVisibility | null,
	/**  自動保存の容量上限（プロジェクトサイズの倍数）。0 は上限なし。選択肢は 0 / 1 / 2 / 5。Phase 2 */
	snapshot_size_cap_x?: number | null,
	/**  AI モデルの指定方法。Phase 2 */
	ai_model_source?: AiModelSource | null,
	/**  任意の GGUF ファイルのパス（`ai_model_source` が `custom-gguf` のとき）。Phase 2 */
	ai_custom_gguf_path?: string | null,
	/**  作業コピー機能を表示する。Phase 3 */
	work_copy_enabled?: boolean | null,
	/**  拡張機能の開発者モード（署名なしの手動導入）。Phase 3 */
	extension_dev_mode?: boolean | null,
	/**  拡張機能の追加索引の URL。空は公式のみ。Phase 4 */
	extension_index_urls?: string[] | null,
	/**  Git LFS を有効にする。Phase 4 */
	git_lfs?: boolean | null,
	/**  用語の表示 */
	term_display?: TermDisplay | null,
};

/**  画面に返す設定 */
export type SettingsView = {
	/**  実際に使う設定。プロジェクトを指定した場合は、全体設定にそのプロジェクトの上書きを重ねたもの */
	settings: AppSettings,
	/**  プロジェクトを指定した場合に、そのプロジェクトで上書きしている項目のキー名 */
	overridden: string[],
};

/**  保存前のサイズ検査で見つかったファイル（保存はしていない） */
export type SizeCheckResult = {
	/**  100MB を超えるため保存できないファイル（E07: 「外して保存」か「キャンセル」） */
	blocked: LargeFileItem[],
	/**  警告閾値を超えるが保存できるファイル（E08: 「このまま保存」か「外す」） */
	warned: LargeFileItem[],
};

/**  飛ばした理由 */
export type SkipKind = 
/**  リンク（シンボリックリンク・ジャンクション）。たどらない */
"link" | 
/**  隠しファイル */
"hidden" | 
/**  OS・Office の一時ファイル */
"os-temp";

/**  飛ばしたもの */
export type SkippedFileItem = {
	/**  ドロップしたものからの相対パス */
	name: string,
	reason: SkipKind,
};

/**  プロジェクトの状態が変わった。UI は `[projectId]` 配下のキャッシュを無効化して再取得する。 */
export type StatusChanged = {
	project_id: string,
};

/**  同期状態が変わった */
export type SyncStateChanged = {
	project_id: string,
	state: SyncStateKind,
	/**  次に自動で再試行する時刻（Unix 秒）。再試行待ちでなければ null */
	retry_at: number | null,
};

/**  同期状態（オフライン・認証失敗は例外ではなく状態として扱う） */
export type SyncStateKind = "idle" | 
/**  オフライン。自動で再試行する */
"offline" | 
/**  再認証が必要 */
"auth-required" | 
/**  変更のぶつかりの解消待ち */
"conflicted" | 
/**  そのほかの失敗。自動で再試行する */
"error";

/**  同期状態 */
export type SyncStatus = {
	unsaved_changes: number,
	upload_pending: number,
	pull_pending: number,
	has_conflicts: boolean,
	is_syncing: boolean,
	/**  前回のアプリ終了で途中で止まった操作の名前（`save` / `pull` など）。なければ null（E15） */
	interrupted_operation: string | null,
	/**  登録したフォルダが見つからない・フォルダでない・リポジトリでない（E11）。true のとき git は実行していない */
	folder_missing: boolean,
	/**  ファイル監視が動いている。true の間、UI は変更一覧の定期的な取り直しをやめる（変更は `files_changed` で届く） */
	watching: boolean,
	/**  最後に自動保存を作った時刻（RFC3339）。まだ一度も作っていなければ null */
	last_auto_snapshot_at: string | null,
};

/**  用語の表示 */
export type TermDisplay = 
/**  平易な表現のみ */
"plain" | 
/**  Git 用語を併記 */
"with-git";

/**  自動保存をタイムラインに出すか */
export type TimelineSnapshots = "collapsed" | "shown" | "hidden";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

